### PR TITLE
Rethink TravisCI configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
- use built-in Travis features
- copy Travis's PHP version: `PHP_VERSION="$(php -r 'echo PHP_VERSION;')"`
- put things in chronological order

### CODE REVIEW

**Comment by szepeviktor** [comment]
Oh no!!!
https://github.com/travis-ci/php-src-builder/pull/24

**Comment by szepeviktor** [comment]
All green 🍏

**Comment by arnaud-lb** [comment]
Thanks !

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
